config/routes.rb
StartAndWin::Application.routes.draw do

  scope :module => "admin" do
    match "/admin" => "admin_home#index", :as => :admin_root
  end

  namespace :admin do
    resources :news_points
    resources :main_categories
    resources :competitions
    resources :difficulty_level_settings, :only => [:index] do
      collection do
        post :update_all_settings
      end
    end
    resources :rating_rate_settings, :only => [:index] do
      collection do
        post :update_all_settings
      end
    end
    resources :experience_settings, :only => [:index] do
      collection do
        post :update_all_settings
      end
    end
    resources :settings, :only => [:index]
    resources :questions do
      collection do
        post :multiple_upload
      end
    end
    get "admin_shared/load_subcategories"
    put "file_upload/async_private_upload"
  end

  namespace :cabinet do
    match 'main' => 'user_cabinet#index', :as => :user_root
    resources :questions do
      member do
        get :close_question
      end
    end
    resources :user_profile, :only => [:edit, :update, :show]
    resources :messages, :only => [:index, :show, :new, :create] do
      post :mark_as, :on => :collection
    end
  end

  scope :module => "front_end" do
    resources :questions, :only => [:index, :show] do
      member do
        get :start_play
        post :process_results
        post :set_rating_and_finish
      end
    end
    match 'about_us' => 'other_pages#about_us'
    match 'contract_us' => 'other_pages#contract_form'
    match 'rules' => 'other_pages#rules'
    match 'send_feedback' => 'other_pages#send_feedback'
  end

  get 'autocomplete_user_login' => 'autocomplete#autocomplete_user_login'
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  get "signup" => "users#new", :as => "signup"
  put "image_uploader/async_upload_with_index"
  post "image_uploader/delete_image"
  match "oauth/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  root :to => 'home#index'

  resources :users
  resources :user_sessions
  resources :password_resets

end

app/views/shared/_category_partial.html.erb
<% if defined?(f) && defined?(model_type)%>
    <div class="inputs category_div" style="margin-top: 15px; margin-bottom: 10px">
      <%= f.fields_for :model_to_main_category do |sub_form| %>
          <%= sub_form.association :main_category, :collection => @categories, :prompt => false %>
      <% end %>
    </div>

    <div class="inputs sub_categories_div">
      <%= render :partial => "/shared/sub_categories", :locals =>
              {:category => @selected_category.present? ? @selected_category : @categories.first, :model => model_type,
               :selected_array => @selected_sub_categories} %>
    </div>
<% end %>

app/views/shared/_errors.html.erb
<% if defined?(object) && object.errors.any? %>
    <% object.errors.full_messages.each do |error| %>
        <p><%= error %></p>
    <% end %>
<% end %>

app/views/shared/_left_tips.html.erb
LEFT USER TIPS

app/views/shared/_login_panel.html.erb
<%= form_for(@user, :url => '/sign_in') do |f| %>
    <div><%= f.label :email %>
      <br/>
      <%= f.email_field :email , :style => 'width:155px'%></div>

    <div><%= f.label 'Пароль' %>
      <br/>
      <%= f.password_field :password, :style => 'width:155px' %></div>

    <div><%= f.submit "Войти" %></div>
<% end %>
  <%= link_to 'Зарегистрироваться', '/sign_up' %>

app/views/shared/_news_point.html.erb
<div class="news">
  <img src="<%= news_point.news_point_image_url %>" class="pic left"/>

  <p class="date margin_top"><%= standard_date(news_point.created_at) %></p>

  <p>
    <%= truncate_html(news_point.description, :length => 250, :omission => "...(<a href='#'>#Читать далее</a>)") %>
  </p>

  <div class="clr"><!-- --></div>
</div>

app/views/shared/_search_form.html.erb
<%= form_for questions_path, :method => :get, :html => {:class => 'search_form'} do %>
    <%= text_field_tag :search_value %>
    <a href="javascript:void(0);" onclick="$('.search_form').submit();" class="css3button">Искать</a>
<% end %>

app/views/shared/_sub_categories.html.erb
<% if defined?(category) && defined?(model) %>
    <% selected_array ||= []  %>
    <% category.sub_categories.each do |sub_category| %>
        <input  id="<%= model %>_sub_categories_attributes_<%= sub_category.id %>" name="<%= model %>[sub_categories_attributes][<%= sub_category.id %>]" type="checkbox" value="0" <%= 'checked=checked'if selected_array.include?(sub_category.id) %>> <%= sub_category.title %>
    <% end %>
<% end %>

app/views/shared/_terms_and_conditions.html.erb
Пользовательсткое соглашение


Белеет парус одинокой
В тумане моря голубом!..
Что ищет он в стране далекой?
Что кинул он в краю родном?..
Играют волны -- ветер свищет,
И мачта гнется и скрыпит...
Увы, -- он счастия не ищет
И не от счастия бежит!

Под ним струя светлей лазури,
Над ним луч солнца золотой...
А он, мятежный, просит бури.
Как будто в бурях есть покой!

app/views/shared/_top_menu.html.erb
<% @menu_entities ||= {'#Главная' => root_path, "#Новости" => '#',"#Соревнования" => '#',
                       "#Форум" => '#',"#Важная информация" => '#',"#О нас" => '#'} %>
<table id="top_menu">
  <tr>
    <% @menu_entities.each do |key,value|%>
        <td>
           <%= link_to  key, value %>
        </td>
    <% end%>
  </tr>
</table>

app/views/shared/_upload_dialog.html.erb
<% if defined?(upload_path) %>
<div id="upload_dialog">
  <%= form_tag  upload_path, :id => 'upload_form', :remote => true do %>
      <%= hidden_field_tag "upload_file_id" %>
      <div id="file_select" style="margin-left: 30%; margin-top: 10%">
        <%= file_field_tag "upload_file" %>
      </div>
  <% end %>
</div>

    <script type="text/javascript">

        <% session_key = Rails.application.config.session_options[:key] %>
        function delete_image(){
            var data = 'id=' +  $("#news_point_image_id").val();
            $.post('<%= image_uploader_delete_image_path %>',data);
        }

        $(function() {
           $('#upload_dialog').dialog({autoOpen:false, modal:true});


            var uploadify_script_data = {};

            // Fetch the CSRF meta tag data
            var csrf_token = $('meta[name=csrf-token]').attr('content');
            var csrf_param = $('meta[name=csrf-param]').attr('content');

            // Now associate the data in the config, encoding the data safely
            uploadify_script_data[csrf_token] = encodeURI(csrf_param);

            // Associate the session information
            uploadify_script_data['<%= session_key %>'] = '<%= cookies[session_key] %>';
            $('#upload_file').uploadify({
                'uploader'  : '/javascripts/uploadify/uploadify.swf',
                'script'    : '<%= admin_file_upload_async_private_upload_path %>.json',
                'cancelImg' : '/images/cancel.png',
                'fileExt'   : '*.yml',
                'fileDesc'  : 'Yml',
                'folder'    : '/uploads',
                'auto'      : true,
                //100Mb limit
                'sizeLimit'   : 104857600,
                'scriptData':
                {
                    '_http_accept': 'application/javascript',
                    '_method': 'put',
                    '<%= session_key %>' : encodeURIComponent('<%= u cookies[session_key] %>'),
                    'authenticity_token': encodeURIComponent('<%= u form_authenticity_token %>')
                },
                'onComplete' : function(event, ID, fileObj, response, data) {
                    var goodies = jQuery.parseJSON(response);
                    if (goodies.status == 1) {
                        $('#upload_file_id').val(goodies.file_id);
                        $('#upload_form').submit();
                    }
                    else {

                    }
                }
            });
        });

    </script>









<% end%>

app/views/shared/_users_left_panel.html.erb
<table>
  <tr>
    <td>
      <img src="/assets/default_avatar.gif" alt="" style="width:70px;">
    </td>
    <td>
      <table>
        <tr>
          <td>user type</td>
        </tr>
        <tr>
          <td><%= current_user.profile.user_name || current_user.email %></td>
        </tr>
        <tr>
          <td>user credits</td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<br/>
<%= link_to 'Зайти как админ', my_admin_root_path, :style => 'color:red;' if current_user.administrator? %>
<br/>
<br/>
<%= link_to '#Текущие соревнования', '#' %><br/>
<%= link_to '#Мои команды', '#' %><br/>
<%= link_to '#Мои друзья', '#' %><br/>
<%= link_to '#Мои фан клубы', '#' %><br/>
<%= link_to '#Мои сообщения', '#' %><br/>
<%= link_to '#Моя статистика', '#' %><br/>
<%= link_to '#Мои настройки', '#' %><br/>
<%= link_to 'Мои профиль', profile_path(:id => current_user.id) %><br/>

<br/> <%= link_to 'Выйти', '/sign_out' %>