config/routes.rb
StartAndWin::Application.routes.draw do

  scope :module => "admin" do
    match "/admin" => "admin_home#index", :as => :admin_root
  end

  namespace :admin do
    resources :news_points
    resources :main_categories
    resources :competitions
    resources :difficulty_level_settings, :only => [:index] do
      collection do
        post :update_all_settings
      end
    end
    resources :rating_rate_settings, :only => [:index] do
      collection do
        post :update_all_settings
      end
    end
    resources :experience_settings, :only => [:index] do
      collection do
        post :update_all_settings
      end
    end
    resources :settings, :only => [:index]
    resources :questions do
      collection do
        post :multiple_upload
      end
    end
    get "admin_shared/load_subcategories"
    put "file_upload/async_private_upload"
  end

  namespace :cabinet do
    match 'main' => 'user_cabinet#index', :as => :user_root
    resources :questions do
      member do
        get :close_question
      end
    end
    resources :user_profile, :only => [:edit, :update, :show]
    resources :messages, :only => [:index, :show, :new, :create] do
      post :mark_as, :on => :collection
    end
  end

  scope :module => "front_end" do
    resources :questions, :only => [:index, :show] do
      member do
        get :start_play
        post :process_results
        post :set_rating_and_finish
      end
    end
    match 'about_us' => 'other_pages#about_us'
    match 'contract_us' => 'other_pages#contract_form'
    match 'rules' => 'other_pages#rules'
    match 'send_feedback' => 'other_pages#send_feedback'
  end

  get 'autocomplete_user_login' => 'autocomplete#autocomplete_user_login'
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  get "signup" => "users#new", :as => "signup"
  put "image_uploader/async_upload_with_index"
  post "image_uploader/delete_image"
  match "oauth/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  root :to => 'home#index'

  resources :users
  resources :user_sessions
  resources :password_resets

end

app/models/difficulty_level_setting.rb
#+---------------------+----------+------+-----+---------+----------------+
#| Field               | Type     | Null | Key | Default | Extra          |
#+---------------------+----------+------+-----+---------+----------------+
#| id                  | int(11)  | NO   | PRI | NULL    | auto_increment |
#| iq_level            | int(11)  | YES  |     | NULL    |                |
#| difficulty_level_id | int(11)  | YES  |     | NULL    |                |
#| created_at          | datetime | YES  |     | NULL    |                |
#| updated_at          | datetime | YES  |     | NULL    |                |
#+---------------------+----------+------+-----+---------+----------------+

class DifficultyLevelSetting < ActiveRecord::Base
  belongs_to :difficulty_level
end

app/controllers/admin/difficulty_level_settings_controller.rb
#encoding: utf-8
class Admin::DifficultyLevelSettingsController < Admin::ApplicationController

  def index
    @difficulty_levels = DifficultyLevel.all
    @difficulty_levels.each do |level|
      level.create_difficulty_level_setting_if_need
    end
  end

  def update_all_settings
    if params[:levels].present? && params[:levels].any?
      params[:levels].each do |level_id, level_params|
        if (level = DifficultyLevel.find_by_id(level_id)).present?
          level.difficulty_level_setting.update_attributes(level_params['difficulty_level_setting'])
        end
      end
      redirect_to admin_difficulty_level_settings_path
    else
      redirect_to admin_root_path, :notice => 'ERROR'
    end
  end
end

app/views/admin/difficulty_level_settings/index.html.erb
<%= form_tag update_all_settings_admin_difficulty_level_settings_path do %>
    <table width="100%">
      <tr>
        <th>Название</th>
        <th>Необходимый уровень IQ</th>
        <th>Максимальное кол-во очков<br/> за участие в соревнований</th>
        <th>Максимальное кол-во очков<br/> за победу в соревнований</th>
        <th>Максимальное кол-во очков<br/> за участие в вопросе</th>
        <th>Максимальное кол-во очков<br/> за победу в вопросе</th>
      </tr>
      <% @difficulty_levels.each do |level| %>
          <tr>
            <td><%= level.name %></td>
            <td>
              <%= text_field_tag "[levels][#{level.id}][difficulty_level_setting][iq_level]", level.difficulty_level_setting.iq_level %>
            </td>
            <td>
              <%= text_field_tag "[levels][#{level.id}][difficulty_level_setting][competition_max_points]", level.difficulty_level_setting.competition_max_points %>
            </td>
            <td>
              <%= text_field_tag "[levels][#{level.id}][difficulty_level_setting][competition_max_win_points]", level.difficulty_level_setting.competition_max_win_points %>
            </td>
            <td>
              <%= text_field_tag "[levels][#{level.id}][difficulty_level_setting][question_max_points]", level.difficulty_level_setting.question_max_points %>
            </td>
            <td>
              <%= text_field_tag "[levels][#{level.id}][difficulty_level_setting][question_max_win_points]", level.difficulty_level_setting.question_max_win_points %>
            </td>

          </tr>
      <% end %>
    </table>
    <%= submit_tag 'Обновить' %>
    <%= link_to 'Отменить', admin_settings_path %>
<% end %>